server:
  port: 7000

spring:
  application:
    name: gulimall-coupon
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://59.110.44.147:3306/gulimall_sms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0

#logging:
#  level:
#    com.atguigu.gulimall: debug

